[사다리 타기] 인상진 미션 제출합니다.
gdsc-skhu-pair-mission/java-ladder pull request #5
Opened 2024-05-12 12:28 UTC by sangjin6439

enum을 사용하기 위해서 Direction의 자료형을 boolean으로 사용하지 않았습니다.
TDD 방식으로 최대한 진행하다가 사다리 타기 부분에서 TDD 방식이 아닌, 구현하고 테스트 코드를 작성했습니다.
한 메서드가 한 가지 기능만 하도록 나누었습니다.

궁금한 점!
일급 컬렉션을 활용했는데 잘 활용했는지 궁금합니다.
테스트 코드 짜는 것에 익숙지 않아서 잘 짜였는지 궁금합니다. 더 잘게 단위 테스트를 진행할 수 있을지 궁금합니다.

2024-05-19 10:33 UTC, vact19 requested changes
리뷰가 늦어 죄송합니다. 고생하셨습니다!

궁금한 점!
> 일급 컬렉션을 활용했는데 잘 활용했는지 궁금합니다.

네! 특별히 문제있는 부분은 보지 못했습니다.

언어에서 제공하는 기본 컬렉션은 (Java의 List 인터페이스처럼)
다음 두가지 특징이 있습니다.
1. 특정 요구사항에 맞춘 로직이 없는 단순 자료 구조이며
2. 자유도가 높습니다.

저는 이를 사용하기 편하게 만드는 과정에서 일급 컬렉션이라는 활용법이 나왔다고 이해했습니다.

단순히 List<User>를 사용하는 상황에서
Users라는 클래스 안에 List<User>를 담는 구조로 변경함으로써
1. users.remove()와 같은 불필요하면서 위험한 코드를 실행할 여지를 막음 (위의 2번 특징인 지나친 자유도 제한의 예시입니다. 물론 생각없이 컬렉션 필드에 getter를 넣어버리면 이 장점이 무의미해지기 때문에 작성하신 코드 예시처럼 count와 username만을 반환하게 하거나, 리스트 전체를 반환하고 싶다면 Collections.unmodifiableList()로 반환하는 방법도 있습니다)
2. size가 MIN_USERS 이상이어야 한다는 로직을 포함할 수 있음 (위의 1번 특징인 '로직이 없는 단순 자료구조라는 점을 극복)
3. 하지만 재사용하지 않는다는 가정 하에, 여러 안전장치를 만드느라 작성할 코드의 양이 조금 더 늘 수 있음

위와 같이 일급 컬렉션의 사용 이유를 알고, 
그에 맞춰 '근거 있는' 일급 컬렉션 클래스를 만들 수 있다면 된다고 생각합니다!

> 테스트 코드 짜는 것에 익숙지 않아서 잘 짜였는지 궁금합니다.
더 잘게 단위 테스트를 진행할 수 있을지 궁금합니다.

이미 테스트가 어느정도 잘 구현된 것 같습니다만,
누락된 부분이라고 한다면 InputView쪽에서의 검증 로직이 되겠네요.

InputView의 validateCreateUser를 검증해야 되는데, 지금은 private이기 때문에
테스트할 수가 없습니다. 그렇다고 해서 테스트 목적으로 접근제어자를 public으로 돌리기도 뭐한 상황입니다.

제가 들은 강의에서 `private method를 테스트하고 싶다면 설계를 변경해야 한다는 신호이다` 라는 말이 나왔었는데요.

InputView에서는 값을 읽어와서 반환만 하고, 별도의 Validator 클래스를 만들어 그곳의 public method로 검증을 하는 식으로 분리를 한다면

책임도 분리되고, 테스트 가능성도 생길 것 같아요!

2024-05-19 10:33 UTC, vact19 commented on src/main/java/controller/GameController.java
> +                .collect(collectingAndThen(toList(), i -> new Users(i)));
필수는 아니지만, 메서드 참조식의 사용도 고려해볼 만 합니다.
`User::new`로도 '스트림의 원소를 User 생성자의 유일한 파라미터로 넣어 생성자를 호출함'을 알 수 있으니까요!

2024-05-19 10:33 UTC, vact19 commented on src/main/java/model/Line.java
> +        createLine(personCount,points);
코드를 읽으면서 이 부분이 좀 의아했습니다.
아래의 createLint()에서 points 필드에 값을 할당하는 로직이 이미 존재합니다.
points를 빈 리스트로 초기화할 필요가 없어 보이네요!

또한 createLine()은 메서드 내부에서 값을 변경하고 있습니다.
이 메서드 내부에서 무슨 일이 일어났는지 구현부를 모두 들여다보지 않아도 되게끔
createLine()이 반환값을 가지게 하면 훨씬 읽기 좋을 것 같네요. 예를 들면
```java
points = new ArrayList<>();
createLine(personCount, points);
```
이거보다
```java
points = createLine(personCount);
```
이게 훨씬 이해하기 쉬워 보이네요.
createLine을 눌러서 무슨 일이 일어나는지 확인할 필요가 없기 때문이죠!

2024-05-19 10:33 UTC, vact19 commented on src/main/java/model/Line.java
> +    }
1. LEFT, NEUTRAL, RIGHT가 존재한다는 점, 
2. prev와 new를 사용해서 연속된 라인이 생기지 않게 검사하는 점, 
3. Direction 리스트의 변수명이 Point로 되어있는 점 등

천천히 읽으면서 분석해야 알 수 있는 부분이 많아서 
제가 이 클래스를 처음 읽었을 때 이해하는 데 시간이 오래 걸렸었습니다.

다른 구현 예시를 보면서 좀 더 단순하게 만들 수 있을지 고민해보거나, 
시간or아이디어가 충분하지 않을 경우에는 전체적인 흐름을 설명하는 주석을 달아주는 것도 좋을 것 같아요!

2024-05-19 10:33 UTC, vact19 commented on src/main/java/model/Line.java
> +        return previousDirection = Direction.NEUTRAL;
여기서 첫째 파라미터인 previousDirection은 없어도 될 것 같아요!
`return Direcetion.LEFT`를 해도 똑같으니까요. 이 부분도 흐름을 이해하기 어려웠던 이유 중에 하나가 되었던 것 같아요!

2024-05-19 10:33 UTC, vact19 commented on src/test/java/ladder/LadderTest.java
> +public class LadderTest {
테스트 클래스는 public이 아니어도 괜찮습니다.
하나의 테스트는 그 자체만으로 독립적인 기능을 수행해야 하고,
이는 LineTest를 작성하다가 `new LadderTest()` 같은 걸 호출할 일은 없다는 것을 의미하니까요!
SonarLint 툴에서도 public keyword를 자제하라고 말하고 있네요. 툴 내부에서 그 이유 또한 설명하니 읽어보세요!

2024-05-19 10:33 UTC, vact19 commented on src/test/java/user/UserTest.java
> +    @DisplayName("유저 이름 생성 시 글자 수 확인")
`글자 수가 ~여야 한다`, `~하지 않으면 예외가 발생한다`와 같이 명시적인 이름을 권장합니다.
구현부를 하나하나 다 뜯지 않고 바깥부분만 읽어도 이해가는 코드를 만들어야 하는데, 이는 테스트 코드도 동일!

2024-05-20 08:36 UTC, vact19 approved these changes
고생하셨습니다!
추가로 개선할 점을 찾자면, 
테스트하기 좋은 구조로 개선하고
Ladder와 Line을 더 이해하기 쉽도록
(즉, 처음 보는 사람이 코드를 보고 로직을 이해하기 쉽게끔) 개선할 수도 있을 것 같습니다.

2024-05-20 08:36 UTC, vact19 commented on src/main/java/model/Direction.java
> +    RIGHT, NEUTRAL
좋습니다! 좌측 방향 이동의 존재가 혼란을 일으키기 쉬웠는데
우측으로 `이동한다/하지 않는다`만이 존재하니 조금 더 이해하기 쉽네요.

2024-05-20 08:37 UTC, merged

2024-05-20 10:11 UTC, sangjin6439 commented
처음 Line을 구현했을 때 나만 이해할 수 있는 코드를 짰던 거 같습니다. 다시금, 남이 알아보기 쉬운 코드에 초점을 두어 코딩을 해야 한다고 느꼈습니다.
추가적으로 말씀하신 테스트하기 좋은 구조도 공부해 보겠습니다.
리뷰 감사합니다!!